// Code generated by protoc-gen-go.
// source: gofigure.proto
// DO NOT EDIT!

/*
Package gofigure is a generated protocol buffer package.

It is generated from these files:
	gofigure.proto

It has these top-level messages:
	ConfigVersion
	ProtoConfig
	YamlConfig
	Config
	CheckConfigRequest
	CheckConfigResponse
	NewConfigRequest
	NewConfigResponse
	GetConfigRequest
	GetConfigResponse
	UpdateConfigRequest
	UpdateConfigResponse
*/
package gofigure

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/struct"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CheckConfigResponse_CheckConfigStatus int32

const (
	CheckConfigResponse_SUCCESS             CheckConfigResponse_CheckConfigStatus = 0
	CheckConfigResponse_ERR_INVALID_SERVICE CheckConfigResponse_CheckConfigStatus = 1
	CheckConfigResponse_ERR_INVALID_CONFIG  CheckConfigResponse_CheckConfigStatus = 2
	CheckConfigResponse_ERR_UNSPECIFIED     CheckConfigResponse_CheckConfigStatus = 3
)

var CheckConfigResponse_CheckConfigStatus_name = map[int32]string{
	0: "SUCCESS",
	1: "ERR_INVALID_SERVICE",
	2: "ERR_INVALID_CONFIG",
	3: "ERR_UNSPECIFIED",
}
var CheckConfigResponse_CheckConfigStatus_value = map[string]int32{
	"SUCCESS":             0,
	"ERR_INVALID_SERVICE": 1,
	"ERR_INVALID_CONFIG":  2,
	"ERR_UNSPECIFIED":     3,
}

func (x CheckConfigResponse_CheckConfigStatus) String() string {
	return proto.EnumName(CheckConfigResponse_CheckConfigStatus_name, int32(x))
}
func (CheckConfigResponse_CheckConfigStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{5, 0}
}

type NewConfigResponse_NewConfigStatus int32

const (
	NewConfigResponse_SUCCESS             NewConfigResponse_NewConfigStatus = 0
	NewConfigResponse_ERR_INVALID_SERVICE NewConfigResponse_NewConfigStatus = 1
	NewConfigResponse_ERR_INVALID_CONFIG  NewConfigResponse_NewConfigStatus = 2
	NewConfigResponse_ERR_UNSPECIFIED     NewConfigResponse_NewConfigStatus = 3
)

var NewConfigResponse_NewConfigStatus_name = map[int32]string{
	0: "SUCCESS",
	1: "ERR_INVALID_SERVICE",
	2: "ERR_INVALID_CONFIG",
	3: "ERR_UNSPECIFIED",
}
var NewConfigResponse_NewConfigStatus_value = map[string]int32{
	"SUCCESS":             0,
	"ERR_INVALID_SERVICE": 1,
	"ERR_INVALID_CONFIG":  2,
	"ERR_UNSPECIFIED":     3,
}

func (x NewConfigResponse_NewConfigStatus) String() string {
	return proto.EnumName(NewConfigResponse_NewConfigStatus_name, int32(x))
}
func (NewConfigResponse_NewConfigStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{7, 0}
}

type GetConfigResponse_GetConfigStatus int32

const (
	GetConfigResponse_SUCCESS             GetConfigResponse_GetConfigStatus = 0
	GetConfigResponse_ERR_INVALID_SERVICE GetConfigResponse_GetConfigStatus = 1
	GetConfigResponse_ERR_INVALID_CONFIG  GetConfigResponse_GetConfigStatus = 2
	GetConfigResponse_ERR_UNSPECIFIED     GetConfigResponse_GetConfigStatus = 3
)

var GetConfigResponse_GetConfigStatus_name = map[int32]string{
	0: "SUCCESS",
	1: "ERR_INVALID_SERVICE",
	2: "ERR_INVALID_CONFIG",
	3: "ERR_UNSPECIFIED",
}
var GetConfigResponse_GetConfigStatus_value = map[string]int32{
	"SUCCESS":             0,
	"ERR_INVALID_SERVICE": 1,
	"ERR_INVALID_CONFIG":  2,
	"ERR_UNSPECIFIED":     3,
}

func (x GetConfigResponse_GetConfigStatus) String() string {
	return proto.EnumName(GetConfigResponse_GetConfigStatus_name, int32(x))
}
func (GetConfigResponse_GetConfigStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{9, 0}
}

type UpdateConfigResponse_UpdateConfigStatus int32

const (
	UpdateConfigResponse_SUCCESS             UpdateConfigResponse_UpdateConfigStatus = 0
	UpdateConfigResponse_ERR_INVALID_SERVICE UpdateConfigResponse_UpdateConfigStatus = 1
	UpdateConfigResponse_ERR_INVALID_CONFIG  UpdateConfigResponse_UpdateConfigStatus = 2
	UpdateConfigResponse_ERR_UNSPECIFIED     UpdateConfigResponse_UpdateConfigStatus = 3
)

var UpdateConfigResponse_UpdateConfigStatus_name = map[int32]string{
	0: "SUCCESS",
	1: "ERR_INVALID_SERVICE",
	2: "ERR_INVALID_CONFIG",
	3: "ERR_UNSPECIFIED",
}
var UpdateConfigResponse_UpdateConfigStatus_value = map[string]int32{
	"SUCCESS":             0,
	"ERR_INVALID_SERVICE": 1,
	"ERR_INVALID_CONFIG":  2,
	"ERR_UNSPECIFIED":     3,
}

func (x UpdateConfigResponse_UpdateConfigStatus) String() string {
	return proto.EnumName(UpdateConfigResponse_UpdateConfigStatus_name, int32(x))
}
func (UpdateConfigResponse_UpdateConfigStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{11, 0}
}

type ConfigVersion struct {
	Id        string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Timestamp int64  `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
}

func (m *ConfigVersion) Reset()                    { *m = ConfigVersion{} }
func (m *ConfigVersion) String() string            { return proto.CompactTextString(m) }
func (*ConfigVersion) ProtoMessage()               {}
func (*ConfigVersion) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ProtoConfig struct {
	Data *google_protobuf.Struct `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
}

func (m *ProtoConfig) Reset()                    { *m = ProtoConfig{} }
func (m *ProtoConfig) String() string            { return proto.CompactTextString(m) }
func (*ProtoConfig) ProtoMessage()               {}
func (*ProtoConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ProtoConfig) GetData() *google_protobuf.Struct {
	if m != nil {
		return m.Data
	}
	return nil
}

type YamlConfig struct {
	RawData []byte `protobuf:"bytes,1,opt,name=raw_data,json=rawData,proto3" json:"raw_data,omitempty"`
}

func (m *YamlConfig) Reset()                    { *m = YamlConfig{} }
func (m *YamlConfig) String() string            { return proto.CompactTextString(m) }
func (*YamlConfig) ProtoMessage()               {}
func (*YamlConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

// Map of Values that represents configuration data for a service
// version specifies version bucket wherein configuration is stored
type Config struct {
	Version *ConfigVersion `protobuf:"bytes,1,opt,name=version" json:"version,omitempty"`
	// Types that are valid to be assigned to AConfig:
	//	*Config_Proto
	//	*Config_Yaml
	AConfig isConfig_AConfig `protobuf_oneof:"a_config"`
}

func (m *Config) Reset()                    { *m = Config{} }
func (m *Config) String() string            { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()               {}
func (*Config) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type isConfig_AConfig interface {
	isConfig_AConfig()
}

type Config_Proto struct {
	Proto *ProtoConfig `protobuf:"bytes,2,opt,name=proto,oneof"`
}
type Config_Yaml struct {
	Yaml *YamlConfig `protobuf:"bytes,3,opt,name=yaml,oneof"`
}

func (*Config_Proto) isConfig_AConfig() {}
func (*Config_Yaml) isConfig_AConfig()  {}

func (m *Config) GetAConfig() isConfig_AConfig {
	if m != nil {
		return m.AConfig
	}
	return nil
}

func (m *Config) GetVersion() *ConfigVersion {
	if m != nil {
		return m.Version
	}
	return nil
}

func (m *Config) GetProto() *ProtoConfig {
	if x, ok := m.GetAConfig().(*Config_Proto); ok {
		return x.Proto
	}
	return nil
}

func (m *Config) GetYaml() *YamlConfig {
	if x, ok := m.GetAConfig().(*Config_Yaml); ok {
		return x.Yaml
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Config) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Config_OneofMarshaler, _Config_OneofUnmarshaler, _Config_OneofSizer, []interface{}{
		(*Config_Proto)(nil),
		(*Config_Yaml)(nil),
	}
}

func _Config_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Config)
	// a_config
	switch x := m.AConfig.(type) {
	case *Config_Proto:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Proto); err != nil {
			return err
		}
	case *Config_Yaml:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Yaml); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Config.AConfig has unexpected type %T", x)
	}
	return nil
}

func _Config_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Config)
	switch tag {
	case 2: // a_config.proto
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ProtoConfig)
		err := b.DecodeMessage(msg)
		m.AConfig = &Config_Proto{msg}
		return true, err
	case 3: // a_config.yaml
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(YamlConfig)
		err := b.DecodeMessage(msg)
		m.AConfig = &Config_Yaml{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Config_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Config)
	// a_config
	switch x := m.AConfig.(type) {
	case *Config_Proto:
		s := proto.Size(x.Proto)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Config_Yaml:
		s := proto.Size(x.Yaml)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// GRPC request to check service configuration
type CheckConfigRequest struct {
	ServiceName string         `protobuf:"bytes,1,opt,name=service_name,json=serviceName" json:"service_name,omitempty"`
	Version     *ConfigVersion `protobuf:"bytes,2,opt,name=version" json:"version,omitempty"`
}

func (m *CheckConfigRequest) Reset()                    { *m = CheckConfigRequest{} }
func (m *CheckConfigRequest) String() string            { return proto.CompactTextString(m) }
func (*CheckConfigRequest) ProtoMessage()               {}
func (*CheckConfigRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *CheckConfigRequest) GetVersion() *ConfigVersion {
	if m != nil {
		return m.Version
	}
	return nil
}

// Used by the client to check its configuration status
type CheckConfigResponse struct {
	Status  CheckConfigResponse_CheckConfigStatus `protobuf:"varint,1,opt,name=status,enum=gofigure.CheckConfigResponse_CheckConfigStatus" json:"status,omitempty"`
	Version *ConfigVersion                        `protobuf:"bytes,2,opt,name=version" json:"version,omitempty"`
}

func (m *CheckConfigResponse) Reset()                    { *m = CheckConfigResponse{} }
func (m *CheckConfigResponse) String() string            { return proto.CompactTextString(m) }
func (*CheckConfigResponse) ProtoMessage()               {}
func (*CheckConfigResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *CheckConfigResponse) GetVersion() *ConfigVersion {
	if m != nil {
		return m.Version
	}
	return nil
}

// Store a new configuration on behalf of a service
type NewConfigRequest struct {
	ServiceName   string  `protobuf:"bytes,1,opt,name=service_name,json=serviceName" json:"service_name,omitempty"`
	Configuration *Config `protobuf:"bytes,2,opt,name=configuration" json:"configuration,omitempty"`
}

func (m *NewConfigRequest) Reset()                    { *m = NewConfigRequest{} }
func (m *NewConfigRequest) String() string            { return proto.CompactTextString(m) }
func (*NewConfigRequest) ProtoMessage()               {}
func (*NewConfigRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *NewConfigRequest) GetConfiguration() *Config {
	if m != nil {
		return m.Configuration
	}
	return nil
}

// Response for new service request
type NewConfigResponse struct {
	Status NewConfigResponse_NewConfigStatus `protobuf:"varint,1,opt,name=status,enum=gofigure.NewConfigResponse_NewConfigStatus" json:"status,omitempty"`
}

func (m *NewConfigResponse) Reset()                    { *m = NewConfigResponse{} }
func (m *NewConfigResponse) String() string            { return proto.CompactTextString(m) }
func (*NewConfigResponse) ProtoMessage()               {}
func (*NewConfigResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

// Returns config given service name and optional version
type GetConfigRequest struct {
	ServiceName string         `protobuf:"bytes,1,opt,name=service_name,json=serviceName" json:"service_name,omitempty"`
	Version     *ConfigVersion `protobuf:"bytes,2,opt,name=version" json:"version,omitempty"`
}

func (m *GetConfigRequest) Reset()                    { *m = GetConfigRequest{} }
func (m *GetConfigRequest) String() string            { return proto.CompactTextString(m) }
func (*GetConfigRequest) ProtoMessage()               {}
func (*GetConfigRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *GetConfigRequest) GetVersion() *ConfigVersion {
	if m != nil {
		return m.Version
	}
	return nil
}

// Response for get service request
type GetConfigResponse struct {
	Status        GetConfigResponse_GetConfigStatus `protobuf:"varint,1,opt,name=status,enum=gofigure.GetConfigResponse_GetConfigStatus" json:"status,omitempty"`
	Configuration *Config                           `protobuf:"bytes,2,opt,name=configuration" json:"configuration,omitempty"`
}

func (m *GetConfigResponse) Reset()                    { *m = GetConfigResponse{} }
func (m *GetConfigResponse) String() string            { return proto.CompactTextString(m) }
func (*GetConfigResponse) ProtoMessage()               {}
func (*GetConfigResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *GetConfigResponse) GetConfiguration() *Config {
	if m != nil {
		return m.Configuration
	}
	return nil
}

// Store new service configuration in service
type UpdateConfigRequest struct {
	ServiceName   string  `protobuf:"bytes,1,opt,name=service_name,json=serviceName" json:"service_name,omitempty"`
	Configuration *Config `protobuf:"bytes,2,opt,name=configuration" json:"configuration,omitempty"`
}

func (m *UpdateConfigRequest) Reset()                    { *m = UpdateConfigRequest{} }
func (m *UpdateConfigRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateConfigRequest) ProtoMessage()               {}
func (*UpdateConfigRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *UpdateConfigRequest) GetConfiguration() *Config {
	if m != nil {
		return m.Configuration
	}
	return nil
}

//  Response for update config request
type UpdateConfigResponse struct {
	Status UpdateConfigResponse_UpdateConfigStatus `protobuf:"varint,1,opt,name=status,enum=gofigure.UpdateConfigResponse_UpdateConfigStatus" json:"status,omitempty"`
}

func (m *UpdateConfigResponse) Reset()                    { *m = UpdateConfigResponse{} }
func (m *UpdateConfigResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateConfigResponse) ProtoMessage()               {}
func (*UpdateConfigResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func init() {
	proto.RegisterType((*ConfigVersion)(nil), "gofigure.ConfigVersion")
	proto.RegisterType((*ProtoConfig)(nil), "gofigure.ProtoConfig")
	proto.RegisterType((*YamlConfig)(nil), "gofigure.YamlConfig")
	proto.RegisterType((*Config)(nil), "gofigure.Config")
	proto.RegisterType((*CheckConfigRequest)(nil), "gofigure.CheckConfigRequest")
	proto.RegisterType((*CheckConfigResponse)(nil), "gofigure.CheckConfigResponse")
	proto.RegisterType((*NewConfigRequest)(nil), "gofigure.NewConfigRequest")
	proto.RegisterType((*NewConfigResponse)(nil), "gofigure.NewConfigResponse")
	proto.RegisterType((*GetConfigRequest)(nil), "gofigure.GetConfigRequest")
	proto.RegisterType((*GetConfigResponse)(nil), "gofigure.GetConfigResponse")
	proto.RegisterType((*UpdateConfigRequest)(nil), "gofigure.UpdateConfigRequest")
	proto.RegisterType((*UpdateConfigResponse)(nil), "gofigure.UpdateConfigResponse")
	proto.RegisterEnum("gofigure.CheckConfigResponse_CheckConfigStatus", CheckConfigResponse_CheckConfigStatus_name, CheckConfigResponse_CheckConfigStatus_value)
	proto.RegisterEnum("gofigure.NewConfigResponse_NewConfigStatus", NewConfigResponse_NewConfigStatus_name, NewConfigResponse_NewConfigStatus_value)
	proto.RegisterEnum("gofigure.GetConfigResponse_GetConfigStatus", GetConfigResponse_GetConfigStatus_name, GetConfigResponse_GetConfigStatus_value)
	proto.RegisterEnum("gofigure.UpdateConfigResponse_UpdateConfigStatus", UpdateConfigResponse_UpdateConfigStatus_name, UpdateConfigResponse_UpdateConfigStatus_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion2

// Client API for GoFigurator service

type GoFiguratorClient interface {
	NewConfig(ctx context.Context, in *NewConfigRequest, opts ...grpc.CallOption) (*NewConfigResponse, error)
	GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigResponse, error)
	UpdateConfig(ctx context.Context, in *UpdateConfigRequest, opts ...grpc.CallOption) (*UpdateConfigResponse, error)
	CheckConfig(ctx context.Context, in *CheckConfigRequest, opts ...grpc.CallOption) (*CheckConfigResponse, error)
}

type goFiguratorClient struct {
	cc *grpc.ClientConn
}

func NewGoFiguratorClient(cc *grpc.ClientConn) GoFiguratorClient {
	return &goFiguratorClient{cc}
}

func (c *goFiguratorClient) NewConfig(ctx context.Context, in *NewConfigRequest, opts ...grpc.CallOption) (*NewConfigResponse, error) {
	out := new(NewConfigResponse)
	err := grpc.Invoke(ctx, "/gofigure.GoFigurator/NewConfig", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goFiguratorClient) GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigResponse, error) {
	out := new(GetConfigResponse)
	err := grpc.Invoke(ctx, "/gofigure.GoFigurator/GetConfig", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goFiguratorClient) UpdateConfig(ctx context.Context, in *UpdateConfigRequest, opts ...grpc.CallOption) (*UpdateConfigResponse, error) {
	out := new(UpdateConfigResponse)
	err := grpc.Invoke(ctx, "/gofigure.GoFigurator/UpdateConfig", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goFiguratorClient) CheckConfig(ctx context.Context, in *CheckConfigRequest, opts ...grpc.CallOption) (*CheckConfigResponse, error) {
	out := new(CheckConfigResponse)
	err := grpc.Invoke(ctx, "/gofigure.GoFigurator/CheckConfig", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GoFigurator service

type GoFiguratorServer interface {
	NewConfig(context.Context, *NewConfigRequest) (*NewConfigResponse, error)
	GetConfig(context.Context, *GetConfigRequest) (*GetConfigResponse, error)
	UpdateConfig(context.Context, *UpdateConfigRequest) (*UpdateConfigResponse, error)
	CheckConfig(context.Context, *CheckConfigRequest) (*CheckConfigResponse, error)
}

func RegisterGoFiguratorServer(s *grpc.Server, srv GoFiguratorServer) {
	s.RegisterService(&_GoFigurator_serviceDesc, srv)
}

func _GoFigurator_NewConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoFiguratorServer).NewConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gofigure.GoFigurator/NewConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoFiguratorServer).NewConfig(ctx, req.(*NewConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoFigurator_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoFiguratorServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gofigure.GoFigurator/GetConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoFiguratorServer).GetConfig(ctx, req.(*GetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoFigurator_UpdateConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoFiguratorServer).UpdateConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gofigure.GoFigurator/UpdateConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoFiguratorServer).UpdateConfig(ctx, req.(*UpdateConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoFigurator_CheckConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoFiguratorServer).CheckConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gofigure.GoFigurator/CheckConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoFiguratorServer).CheckConfig(ctx, req.(*CheckConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GoFigurator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gofigure.GoFigurator",
	HandlerType: (*GoFiguratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewConfig",
			Handler:    _GoFigurator_NewConfig_Handler,
		},
		{
			MethodName: "GetConfig",
			Handler:    _GoFigurator_GetConfig_Handler,
		},
		{
			MethodName: "UpdateConfig",
			Handler:    _GoFigurator_UpdateConfig_Handler,
		},
		{
			MethodName: "CheckConfig",
			Handler:    _GoFigurator_CheckConfig_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 638 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xbc, 0x55, 0xcb, 0x6e, 0xd3, 0x40,
	0x14, 0x8d, 0xd3, 0xd2, 0xc7, 0x75, 0x1f, 0xee, 0xa4, 0xd0, 0x52, 0x5a, 0x04, 0xde, 0x80, 0xa8,
	0x48, 0xd4, 0x20, 0x58, 0x20, 0xb1, 0x00, 0xd7, 0x09, 0x96, 0xaa, 0xb4, 0x1a, 0xab, 0x95, 0x58,
	0x45, 0x4e, 0x32, 0x71, 0x0c, 0x71, 0xc6, 0xf8, 0xd1, 0xaa, 0xbf, 0xc3, 0x77, 0x20, 0x3e, 0x80,
	0x0f, 0x42, 0x62, 0xc7, 0x64, 0xec, 0xc6, 0x63, 0xbb, 0x0d, 0x50, 0x29, 0x5d, 0x25, 0x73, 0xe6,
	0xdc, 0x73, 0xef, 0x3d, 0x73, 0x67, 0x0c, 0x6b, 0x36, 0xed, 0x3b, 0x76, 0xe4, 0x93, 0xaa, 0xe7,
	0xd3, 0x90, 0xa2, 0xa5, 0xab, 0xf5, 0xce, 0x6b, 0xdb, 0x09, 0x07, 0x51, 0xa7, 0xda, 0xa5, 0x6e,
	0xcd, 0xa6, 0x43, 0x6b, 0x64, 0xd7, 0x38, 0xa5, 0x13, 0xf5, 0x6b, 0x5e, 0x78, 0xe9, 0x91, 0xa0,
	0x16, 0x84, 0x7e, 0xd4, 0x0d, 0x93, 0x9f, 0x58, 0x40, 0x7d, 0x07, 0xab, 0x1a, 0x1d, 0x31, 0x8d,
	0x33, 0xe2, 0x07, 0x0e, 0x1d, 0xa1, 0x35, 0x28, 0x3b, 0xbd, 0x6d, 0xe9, 0x89, 0xf4, 0x7c, 0x19,
	0xb3, 0x7f, 0x68, 0x17, 0x96, 0x43, 0xc7, 0x25, 0x41, 0x68, 0xb9, 0xde, 0x76, 0x99, 0xc1, 0x73,
	0x38, 0x05, 0xd4, 0xb7, 0x20, 0x9f, 0x8c, 0x75, 0x62, 0x0d, 0xb4, 0x0f, 0xf3, 0x3d, 0x2b, 0xb4,
	0x78, 0xb8, 0x5c, 0xdf, 0xaa, 0xda, 0x94, 0xda, 0xc3, 0xa4, 0x56, 0x56, 0x48, 0xd5, 0xe4, 0xa9,
	0x31, 0x27, 0xa9, 0xcf, 0x00, 0x3e, 0x59, 0xee, 0x30, 0x09, 0x7d, 0x08, 0x4b, 0xbe, 0x75, 0xd1,
	0x9e, 0x84, 0xaf, 0xe0, 0x45, 0xb6, 0x3e, 0x1c, 0x13, 0xbf, 0x49, 0xb0, 0x90, 0xb0, 0x0e, 0x60,
	0xf1, 0x3c, 0x2e, 0x54, 0xc8, 0x91, 0x38, 0x92, 0xe9, 0x03, 0x5f, 0xf1, 0xd0, 0x4b, 0xb8, 0xc7,
	0xf3, 0xf3, 0xe2, 0xe5, 0xfa, 0xfd, 0x34, 0x40, 0xa8, 0xfc, 0x63, 0x09, 0xc7, 0x2c, 0xf4, 0x02,
	0xe6, 0x2f, 0x59, 0x55, 0xdb, 0x73, 0x9c, 0xbd, 0x99, 0xb2, 0xd3, 0x5a, 0x19, 0x99, 0x73, 0x3e,
	0x00, 0x2c, 0x59, 0xed, 0x2e, 0xc7, 0xd4, 0xcf, 0x80, 0xb4, 0x01, 0xe9, 0x7e, 0x89, 0x29, 0x98,
	0x7c, 0x8d, 0x98, 0x45, 0xe8, 0x29, 0xac, 0x04, 0xc4, 0x3f, 0x77, 0xba, 0xa4, 0x3d, 0xb2, 0x5c,
	0x92, 0xf8, 0x2a, 0x27, 0x58, 0x8b, 0x41, 0x62, 0x4b, 0xe5, 0x7f, 0x6b, 0x49, 0xfd, 0x2d, 0x41,
	0x25, 0x93, 0x2c, 0xf0, 0xe8, 0x28, 0x20, 0xa8, 0x09, 0x0b, 0xec, 0x58, 0xc2, 0x28, 0xe0, 0x79,
	0xd6, 0xea, 0x35, 0x41, 0xa9, 0x48, 0x17, 0x31, 0x93, 0x87, 0xe1, 0x24, 0xfc, 0x36, 0x35, 0xf5,
	0x61, 0xa3, 0xa0, 0x87, 0x64, 0x58, 0x34, 0x4f, 0x35, 0x4d, 0x37, 0x4d, 0xa5, 0x84, 0xb6, 0xa0,
	0xa2, 0x63, 0xdc, 0x36, 0x5a, 0x67, 0xef, 0x8f, 0x8c, 0xc3, 0xb6, 0xa9, 0xe3, 0x33, 0x43, 0xd3,
	0x15, 0x09, 0x3d, 0x00, 0x24, 0x6e, 0x68, 0xc7, 0xad, 0x86, 0xd1, 0x54, 0xca, 0xa8, 0x02, 0xeb,
	0x63, 0xfc, 0xb4, 0x65, 0x9e, 0xe8, 0x9a, 0xd1, 0x30, 0xf4, 0x43, 0x65, 0x4e, 0x75, 0x41, 0x69,
	0x91, 0x8b, 0xff, 0x76, 0xf9, 0x0d, 0xac, 0xc6, 0x07, 0x15, 0xf9, 0x56, 0x98, 0xf6, 0xa5, 0xe4,
	0xfb, 0xc2, 0x59, 0x9a, 0xfa, 0x43, 0x82, 0x0d, 0x21, 0x5f, 0x62, 0xb4, 0x96, 0x33, 0x7a, 0x3f,
	0x95, 0x29, 0x90, 0x53, 0x24, 0x6b, 0xb2, 0xda, 0x83, 0xf5, 0xdc, 0xd6, 0x2c, 0xfc, 0x1a, 0x80,
	0xd2, 0x24, 0xe1, 0x5d, 0x4c, 0xe5, 0x2f, 0x66, 0x95, 0x90, 0xea, 0xef, 0x56, 0x15, 0xc8, 0x29,
	0x92, 0x9b, 0xc7, 0xdb, 0x9e, 0x1e, 0xb3, 0x38, 0x27, 0x39, 0x0b, 0x8b, 0x3d, 0xa8, 0x9c, 0x7a,
	0xec, 0xe1, 0x22, 0x77, 0x36, 0x95, 0x3f, 0x25, 0xd8, 0xcc, 0xa6, 0x4c, 0xdc, 0x36, 0x72, 0x6e,
	0x1f, 0xa4, 0x4a, 0xd7, 0xf1, 0x33, 0x60, 0x6e, 0x3c, 0x6d, 0x40, 0xc5, 0xdd, 0x19, 0xd8, 0x57,
	0xff, 0x5e, 0x06, 0xb9, 0x49, 0x1b, 0x71, 0x77, 0xd4, 0x47, 0x0d, 0x58, 0x9e, 0xdc, 0x0b, 0xb4,
	0x73, 0xed, 0xcd, 0xe2, 0x06, 0xef, 0x3c, 0x9a, 0x72, 0xeb, 0xd4, 0xd2, 0x58, 0x67, 0x72, 0xf8,
	0xa2, 0x4e, 0xfe, 0x3a, 0x88, 0x3a, 0x85, 0x91, 0x64, 0x3a, 0xc7, 0xb0, 0x22, 0x1a, 0x81, 0xf6,
	0x6e, 0xf2, 0x34, 0x56, 0x7b, 0x3c, 0xdd, 0x72, 0x26, 0x78, 0x04, 0xb2, 0xf0, 0x54, 0xa2, 0xdd,
	0x1b, 0x5e, 0xe9, 0x58, 0x6e, 0x6f, 0xea, 0x1b, 0xae, 0x96, 0x3a, 0x0b, 0xfc, 0xbb, 0xf5, 0xea,
	0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb8, 0xbd, 0x43, 0x6b, 0x1b, 0x08, 0x00, 0x00,
}
