// Code generated by protoc-gen-go.
// source: gofigure.proto
// DO NOT EDIT!

/*
Package gofigure is a generated protocol buffer package.

It is generated from these files:
	gofigure.proto

It has these top-level messages:
	Config
	ConfigCheckRequest
	ConfigCheckResponse
	NewRequest
	NewConfigRequest
	NewConfigResponse
	GetConfigRequest
	GetConfigResponse
	UpdateConfigRequest
	UpdateConfigResponse
*/
package gofigure

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/struct"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ConfigCheckResponse_ConfigStatus int32

const (
	ConfigCheckResponse_OLD     ConfigCheckResponse_ConfigStatus = 0
	ConfigCheckResponse_CURRENT ConfigCheckResponse_ConfigStatus = 1
	ConfigCheckResponse_FUTURE  ConfigCheckResponse_ConfigStatus = 2
	ConfigCheckResponse_INVALID ConfigCheckResponse_ConfigStatus = 3
)

var ConfigCheckResponse_ConfigStatus_name = map[int32]string{
	0: "OLD",
	1: "CURRENT",
	2: "FUTURE",
	3: "INVALID",
}
var ConfigCheckResponse_ConfigStatus_value = map[string]int32{
	"OLD":     0,
	"CURRENT": 1,
	"FUTURE":  2,
	"INVALID": 3,
}

func (x ConfigCheckResponse_ConfigStatus) String() string {
	return proto.EnumName(ConfigCheckResponse_ConfigStatus_name, int32(x))
}
func (ConfigCheckResponse_ConfigStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{2, 0}
}

type NewConfigResponse_NewConfigStatus int32

const (
	NewConfigResponse_SUCCESS       NewConfigResponse_NewConfigStatus = 0
	NewConfigResponse_ERREXISTS     NewConfigResponse_NewConfigStatus = 1
	NewConfigResponse_ERRUSPECIFIED NewConfigResponse_NewConfigStatus = 2
)

var NewConfigResponse_NewConfigStatus_name = map[int32]string{
	0: "SUCCESS",
	1: "ERREXISTS",
	2: "ERRUSPECIFIED",
}
var NewConfigResponse_NewConfigStatus_value = map[string]int32{
	"SUCCESS":       0,
	"ERREXISTS":     1,
	"ERRUSPECIFIED": 2,
}

func (x NewConfigResponse_NewConfigStatus) String() string {
	return proto.EnumName(NewConfigResponse_NewConfigStatus_name, int32(x))
}
func (NewConfigResponse_NewConfigStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{5, 0}
}

type GetConfigResponse_GetConfigStatus int32

const (
	GetConfigResponse_SUCCESS       GetConfigResponse_GetConfigStatus = 0
	GetConfigResponse_ERRINVALID    GetConfigResponse_GetConfigStatus = 1
	GetConfigResponse_ERRUSPECIFIED GetConfigResponse_GetConfigStatus = 2
)

var GetConfigResponse_GetConfigStatus_name = map[int32]string{
	0: "SUCCESS",
	1: "ERRINVALID",
	2: "ERRUSPECIFIED",
}
var GetConfigResponse_GetConfigStatus_value = map[string]int32{
	"SUCCESS":       0,
	"ERRINVALID":    1,
	"ERRUSPECIFIED": 2,
}

func (x GetConfigResponse_GetConfigStatus) String() string {
	return proto.EnumName(GetConfigResponse_GetConfigStatus_name, int32(x))
}
func (GetConfigResponse_GetConfigStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{7, 0}
}

type UpdateConfigResponse_UpdateConfigStatus int32

const (
	UpdateConfigResponse_SUCCESS       UpdateConfigResponse_UpdateConfigStatus = 0
	UpdateConfigResponse_ERRINVALID    UpdateConfigResponse_UpdateConfigStatus = 1
	UpdateConfigResponse_ERRUSPECIFIED UpdateConfigResponse_UpdateConfigStatus = 2
)

var UpdateConfigResponse_UpdateConfigStatus_name = map[int32]string{
	0: "SUCCESS",
	1: "ERRINVALID",
	2: "ERRUSPECIFIED",
}
var UpdateConfigResponse_UpdateConfigStatus_value = map[string]int32{
	"SUCCESS":       0,
	"ERRINVALID":    1,
	"ERRUSPECIFIED": 2,
}

func (x UpdateConfigResponse_UpdateConfigStatus) String() string {
	return proto.EnumName(UpdateConfigResponse_UpdateConfigStatus_name, int32(x))
}
func (UpdateConfigResponse_UpdateConfigStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{9, 0}
}

// Map of Values that represents configuration data for a service
// version specifies version bucket wherein configuration is stored
type Config struct {
	Version       int64                   `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	Configuration *google_protobuf.Struct `protobuf:"bytes,2,opt,name=configuration" json:"configuration,omitempty"`
}

func (m *Config) Reset()                    { *m = Config{} }
func (m *Config) String() string            { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()               {}
func (*Config) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Config) GetConfiguration() *google_protobuf.Struct {
	if m != nil {
		return m.Configuration
	}
	return nil
}

// GRPC request to check service configuration
// server uses version number to tell client if its config is current
// incrementing version number corresponds to boltdb bucket containing serialized config within a services' bucket
// Highest version number represents current configuration version
type ConfigCheckRequest struct {
	Service string `protobuf:"bytes,1,opt,name=service" json:"service,omitempty"`
	Version int64  `protobuf:"varint,2,opt,name=version" json:"version,omitempty"`
}

func (m *ConfigCheckRequest) Reset()                    { *m = ConfigCheckRequest{} }
func (m *ConfigCheckRequest) String() string            { return proto.CompactTextString(m) }
func (*ConfigCheckRequest) ProtoMessage()               {}
func (*ConfigCheckRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// Used by the client to check its configuration status
type ConfigCheckResponse struct {
	Status ConfigCheckResponse_ConfigStatus `protobuf:"varint,1,opt,name=status,enum=gofigure.ConfigCheckResponse_ConfigStatus" json:"status,omitempty"`
}

func (m *ConfigCheckResponse) Reset()                    { *m = ConfigCheckResponse{} }
func (m *ConfigCheckResponse) String() string            { return proto.CompactTextString(m) }
func (*ConfigCheckResponse) ProtoMessage()               {}
func (*ConfigCheckResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

// Creates a new configuration for the given service
type NewRequest struct {
	ServiceName   string  `protobuf:"bytes,1,opt,name=service_name,json=serviceName" json:"service_name,omitempty"`
	Configuration *Config `protobuf:"bytes,2,opt,name=configuration" json:"configuration,omitempty"`
}

func (m *NewRequest) Reset()                    { *m = NewRequest{} }
func (m *NewRequest) String() string            { return proto.CompactTextString(m) }
func (*NewRequest) ProtoMessage()               {}
func (*NewRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *NewRequest) GetConfiguration() *Config {
	if m != nil {
		return m.Configuration
	}
	return nil
}

// Store a new configuration on behalf of a service
type NewConfigRequest struct {
	ServiceName   string  `protobuf:"bytes,1,opt,name=service_name,json=serviceName" json:"service_name,omitempty"`
	Configuration *Config `protobuf:"bytes,2,opt,name=configuration" json:"configuration,omitempty"`
}

func (m *NewConfigRequest) Reset()                    { *m = NewConfigRequest{} }
func (m *NewConfigRequest) String() string            { return proto.CompactTextString(m) }
func (*NewConfigRequest) ProtoMessage()               {}
func (*NewConfigRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *NewConfigRequest) GetConfiguration() *Config {
	if m != nil {
		return m.Configuration
	}
	return nil
}

// Response for new service request
type NewConfigResponse struct {
	Status NewConfigResponse_NewConfigStatus `protobuf:"varint,1,opt,name=status,enum=gofigure.NewConfigResponse_NewConfigStatus" json:"status,omitempty"`
}

func (m *NewConfigResponse) Reset()                    { *m = NewConfigResponse{} }
func (m *NewConfigResponse) String() string            { return proto.CompactTextString(m) }
func (*NewConfigResponse) ProtoMessage()               {}
func (*NewConfigResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

// Returns config given service name and optional version
type GetConfigRequest struct {
	ServiceName string `protobuf:"bytes,1,opt,name=service_name,json=serviceName" json:"service_name,omitempty"`
	Version     int64  `protobuf:"varint,2,opt,name=version" json:"version,omitempty"`
}

func (m *GetConfigRequest) Reset()                    { *m = GetConfigRequest{} }
func (m *GetConfigRequest) String() string            { return proto.CompactTextString(m) }
func (*GetConfigRequest) ProtoMessage()               {}
func (*GetConfigRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

// Response for get service request
type GetConfigResponse struct {
	Status        GetConfigResponse_GetConfigStatus `protobuf:"varint,1,opt,name=status,enum=gofigure.GetConfigResponse_GetConfigStatus" json:"status,omitempty"`
	Configuration *Config                           `protobuf:"bytes,2,opt,name=configuration" json:"configuration,omitempty"`
}

func (m *GetConfigResponse) Reset()                    { *m = GetConfigResponse{} }
func (m *GetConfigResponse) String() string            { return proto.CompactTextString(m) }
func (*GetConfigResponse) ProtoMessage()               {}
func (*GetConfigResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *GetConfigResponse) GetConfiguration() *Config {
	if m != nil {
		return m.Configuration
	}
	return nil
}

// Store new service configuration in service/(version+1)
type UpdateConfigRequest struct {
	ServiceName   string  `protobuf:"bytes,1,opt,name=service_name,json=serviceName" json:"service_name,omitempty"`
	Configuration *Config `protobuf:"bytes,2,opt,name=configuration" json:"configuration,omitempty"`
}

func (m *UpdateConfigRequest) Reset()                    { *m = UpdateConfigRequest{} }
func (m *UpdateConfigRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateConfigRequest) ProtoMessage()               {}
func (*UpdateConfigRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *UpdateConfigRequest) GetConfiguration() *Config {
	if m != nil {
		return m.Configuration
	}
	return nil
}

//  Response for update config request
type UpdateConfigResponse struct {
	Status UpdateConfigResponse_UpdateConfigStatus `protobuf:"varint,1,opt,name=status,enum=gofigure.UpdateConfigResponse_UpdateConfigStatus" json:"status,omitempty"`
}

func (m *UpdateConfigResponse) Reset()                    { *m = UpdateConfigResponse{} }
func (m *UpdateConfigResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateConfigResponse) ProtoMessage()               {}
func (*UpdateConfigResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func init() {
	proto.RegisterType((*Config)(nil), "gofigure.Config")
	proto.RegisterType((*ConfigCheckRequest)(nil), "gofigure.ConfigCheckRequest")
	proto.RegisterType((*ConfigCheckResponse)(nil), "gofigure.ConfigCheckResponse")
	proto.RegisterType((*NewRequest)(nil), "gofigure.NewRequest")
	proto.RegisterType((*NewConfigRequest)(nil), "gofigure.NewConfigRequest")
	proto.RegisterType((*NewConfigResponse)(nil), "gofigure.NewConfigResponse")
	proto.RegisterType((*GetConfigRequest)(nil), "gofigure.GetConfigRequest")
	proto.RegisterType((*GetConfigResponse)(nil), "gofigure.GetConfigResponse")
	proto.RegisterType((*UpdateConfigRequest)(nil), "gofigure.UpdateConfigRequest")
	proto.RegisterType((*UpdateConfigResponse)(nil), "gofigure.UpdateConfigResponse")
	proto.RegisterEnum("gofigure.ConfigCheckResponse_ConfigStatus", ConfigCheckResponse_ConfigStatus_name, ConfigCheckResponse_ConfigStatus_value)
	proto.RegisterEnum("gofigure.NewConfigResponse_NewConfigStatus", NewConfigResponse_NewConfigStatus_name, NewConfigResponse_NewConfigStatus_value)
	proto.RegisterEnum("gofigure.GetConfigResponse_GetConfigStatus", GetConfigResponse_GetConfigStatus_name, GetConfigResponse_GetConfigStatus_value)
	proto.RegisterEnum("gofigure.UpdateConfigResponse_UpdateConfigStatus", UpdateConfigResponse_UpdateConfigStatus_name, UpdateConfigResponse_UpdateConfigStatus_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion2

// Client API for GoFigurator service

type GoFiguratorClient interface {
	NewConfig(ctx context.Context, in *NewConfigRequest, opts ...grpc.CallOption) (*NewConfigResponse, error)
	GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigResponse, error)
	UpdateConfig(ctx context.Context, in *UpdateConfigRequest, opts ...grpc.CallOption) (*UpdateConfigResponse, error)
}

type goFiguratorClient struct {
	cc *grpc.ClientConn
}

func NewGoFiguratorClient(cc *grpc.ClientConn) GoFiguratorClient {
	return &goFiguratorClient{cc}
}

func (c *goFiguratorClient) NewConfig(ctx context.Context, in *NewConfigRequest, opts ...grpc.CallOption) (*NewConfigResponse, error) {
	out := new(NewConfigResponse)
	err := grpc.Invoke(ctx, "/gofigure.GoFigurator/NewConfig", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goFiguratorClient) GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigResponse, error) {
	out := new(GetConfigResponse)
	err := grpc.Invoke(ctx, "/gofigure.GoFigurator/GetConfig", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goFiguratorClient) UpdateConfig(ctx context.Context, in *UpdateConfigRequest, opts ...grpc.CallOption) (*UpdateConfigResponse, error) {
	out := new(UpdateConfigResponse)
	err := grpc.Invoke(ctx, "/gofigure.GoFigurator/UpdateConfig", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GoFigurator service

type GoFiguratorServer interface {
	NewConfig(context.Context, *NewConfigRequest) (*NewConfigResponse, error)
	GetConfig(context.Context, *GetConfigRequest) (*GetConfigResponse, error)
	UpdateConfig(context.Context, *UpdateConfigRequest) (*UpdateConfigResponse, error)
}

func RegisterGoFiguratorServer(s *grpc.Server, srv GoFiguratorServer) {
	s.RegisterService(&_GoFigurator_serviceDesc, srv)
}

func _GoFigurator_NewConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoFiguratorServer).NewConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gofigure.GoFigurator/NewConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoFiguratorServer).NewConfig(ctx, req.(*NewConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoFigurator_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoFiguratorServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gofigure.GoFigurator/GetConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoFiguratorServer).GetConfig(ctx, req.(*GetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoFigurator_UpdateConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoFiguratorServer).UpdateConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gofigure.GoFigurator/UpdateConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoFiguratorServer).UpdateConfig(ctx, req.(*UpdateConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GoFigurator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gofigure.GoFigurator",
	HandlerType: (*GoFiguratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewConfig",
			Handler:    _GoFigurator_NewConfig_Handler,
		},
		{
			MethodName: "GetConfig",
			Handler:    _GoFigurator_GetConfig_Handler,
		},
		{
			MethodName: "UpdateConfig",
			Handler:    _GoFigurator_UpdateConfig_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 537 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xbc, 0x94, 0xdd, 0x8a, 0xd3, 0x40,
	0x14, 0xc7, 0x9b, 0x16, 0x5a, 0x7b, 0xfa, 0xb1, 0xd9, 0x59, 0xc1, 0xa5, 0xa2, 0x68, 0xae, 0x44,
	0x21, 0xc5, 0x8a, 0xde, 0x2d, 0xb8, 0xa6, 0xe9, 0x1a, 0x58, 0x5a, 0x49, 0x1a, 0xf1, 0x4e, 0xd2,
	0x38, 0x9b, 0x2d, 0x6e, 0x33, 0x31, 0x33, 0x59, 0xf1, 0x4d, 0xc4, 0x17, 0xf0, 0x81, 0x7c, 0x0f,
	0x9f, 0xc1, 0x49, 0x3a, 0x69, 0x93, 0x69, 0x76, 0x65, 0x05, 0xf7, 0xaa, 0x9c, 0x8f, 0xfc, 0xcf,
	0x39, 0xbf, 0xf9, 0x53, 0xe8, 0x07, 0xe4, 0x6c, 0x19, 0x24, 0x31, 0xd6, 0xa3, 0x98, 0x30, 0x82,
	0xee, 0xe4, 0xf1, 0xe0, 0x65, 0xb0, 0x64, 0xe7, 0xc9, 0x42, 0xf7, 0xc9, 0x6a, 0x18, 0x90, 0x0b,
	0x2f, 0x0c, 0x86, 0x59, 0xcb, 0x22, 0x39, 0x1b, 0x46, 0xec, 0x5b, 0x84, 0xe9, 0x90, 0xb2, 0x38,
	0xf1, 0x99, 0xf8, 0x59, 0x0b, 0x68, 0x1e, 0x34, 0x0d, 0x12, 0x72, 0x0d, 0x74, 0x08, 0xad, 0x4b,
	0x1c, 0xd3, 0x25, 0x09, 0x0f, 0x95, 0x47, 0xca, 0x93, 0x86, 0x9d, 0x87, 0xe8, 0x08, 0x7a, 0x7e,
	0xd6, 0x93, 0xc4, 0x1e, 0x4b, 0xeb, 0x75, 0x5e, 0xef, 0x8c, 0xee, 0xe9, 0x01, 0x21, 0xc1, 0x85,
	0x58, 0x85, 0xcf, 0xd1, 0x9d, 0x4c, 0xd9, 0x2e, 0x77, 0x6b, 0x6f, 0x01, 0xad, 0x47, 0x18, 0xe7,
	0xd8, 0xff, 0x6c, 0xe3, 0x2f, 0x09, 0xa6, 0x2c, 0x1d, 0x47, 0x71, 0x7c, 0xb9, 0xf4, 0x71, 0x36,
	0xae, 0x6d, 0xe7, 0x61, 0x71, 0x91, 0x7a, 0x69, 0x11, 0xed, 0xbb, 0x02, 0x07, 0x25, 0x29, 0x1a,
	0x91, 0x90, 0x62, 0xf4, 0x06, 0x9a, 0x94, 0x79, 0x2c, 0xa1, 0x99, 0x54, 0x7f, 0xf4, 0x54, 0xdf,
	0x60, 0xaa, 0x68, 0x17, 0x39, 0x27, 0xfb, 0xc2, 0x16, 0x5f, 0x6a, 0x47, 0xd0, 0x2d, 0xe6, 0x51,
	0x0b, 0x1a, 0xb3, 0xd3, 0xb1, 0x5a, 0x43, 0x1d, 0x68, 0x19, 0xae, 0x6d, 0x9b, 0xd3, 0xb9, 0xaa,
	0x20, 0x80, 0xe6, 0xc4, 0x9d, 0xbb, 0xb6, 0xa9, 0xd6, 0xd3, 0x82, 0x35, 0x7d, 0x7f, 0x7c, 0x6a,
	0x8d, 0xd5, 0x86, 0x16, 0x00, 0x4c, 0xf1, 0xd7, 0xfc, 0xb8, 0xc7, 0xd0, 0x15, 0xd7, 0x7c, 0x0c,
	0xbd, 0x55, 0x7e, 0x61, 0x47, 0xe4, 0xa6, 0x3c, 0x85, 0x5e, 0x55, 0x43, 0x55, 0xe5, 0xd5, 0x65,
	0x9a, 0x2b, 0x50, 0xf9, 0x20, 0x51, 0xfb, 0xff, 0xe3, 0x7e, 0x28, 0xb0, 0x5f, 0x98, 0x27, 0x80,
	0x1b, 0x12, 0xf0, 0x67, 0x5b, 0x99, 0x9d, 0xe6, 0x6d, 0x46, 0x22, 0xfe, 0x1a, 0xf6, 0xa4, 0x52,
	0x8a, 0xd4, 0x71, 0x0d, 0xc3, 0x74, 0x1c, 0x0e, 0xbe, 0x07, 0x6d, 0x93, 0x73, 0xff, 0x60, 0x39,
	0x73, 0x87, 0xa3, 0xdf, 0x87, 0x1e, 0x0f, 0x5d, 0xe7, 0x9d, 0x69, 0x58, 0x13, 0xcb, 0x1c, 0xab,
	0x75, 0x6d, 0x06, 0xea, 0x09, 0x66, 0x37, 0x66, 0x71, 0xb5, 0xc1, 0x7e, 0xf1, 0x6b, 0x0b, 0x8a,
	0x7f, 0xbf, 0x76, 0xa7, 0x79, 0x9b, 0x29, 0x5f, 0xfb, 0xcf, 0x0f, 0x70, 0x0c, 0x7b, 0x92, 0x64,
	0x99, 0x52, 0x1f, 0x80, 0x63, 0xc9, 0x8d, 0x58, 0x89, 0x29, 0x82, 0x03, 0x37, 0xfa, 0xe4, 0x31,
	0x7c, 0x6b, 0xae, 0xf9, 0xa9, 0xc0, 0xdd, 0xf2, 0x48, 0x81, 0xd2, 0x92, 0x50, 0x3e, 0xdf, 0x2a,
	0x55, 0xf5, 0x97, 0x92, 0x92, 0x7d, 0xc6, 0x80, 0x76, 0xab, 0x37, 0x65, 0x33, 0xfa, 0xad, 0x40,
	0xe7, 0x84, 0x4c, 0xd6, 0xab, 0x93, 0x18, 0x4d, 0xa0, 0xbd, 0x31, 0x25, 0x1a, 0x54, 0xda, 0x3a,
	0xa3, 0x37, 0xb8, 0x7f, 0x8d, 0xe5, 0xb5, 0x5a, 0xaa, 0xb3, 0x79, 0xb6, 0xa2, 0x8e, 0xec, 0xd7,
	0xa2, 0xce, 0x8e, 0x99, 0xb8, 0xce, 0x0c, 0xba, 0xc5, 0x2b, 0xd1, 0x83, 0xab, 0x80, 0xad, 0xd5,
	0x1e, 0x5e, 0xcf, 0x53, 0xab, 0x2d, 0x9a, 0xd9, 0xbf, 0xf5, 0x8b, 0x3f, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x8f, 0x99, 0xa6, 0x34, 0x4a, 0x06, 0x00, 0x00,
}
